FROM rust:1.80 as builder
WORKDIR /usr/src/app
COPY . .
RUN cargo build --release

FROM debian:buster-slim
RUN apt-get update && apt-get install -y \
    python3 \
    python3-pip \
    ffmpeg \
    && pip3 install yt-dlp \
    && rm -rf /var/lib/apt/lists/*
COPY --from=builder /usr/src/app/target/release/telegram-yt-bot /usr/local/bin/telegram-yt-bot
CMD ["telegram-yt-bot"]